### ISSUE TITLE
Production of trees 80X_V3

### ISSUE THREAD

**Issue by emanueledimarco** [emanueledimarco/cmgtools-lite#26]
V3 production is made with 
- cmgtools-lite c8fee73
- cmg-cmssw [1952ae6](https://github.com/emanueledimarco/cmg-cmssw/commit/1952ae69b7d1215d5ff9a4709581483205fa5f08)

This has: 
- reduction of size (0.7 kB/event on MC without LHEweights)
- LHE weights make trees big (~2.3 kB/event on Wjets): saved only for signal
- addition of GenPart collection, saving the incoming partons
- save the HLT bits

**Comment by emanueledimarco** [comment]
Status: 
- WJets (mc@NLO and Madgraph done)
- MC (DY, other backgrounds including QCD samples mu- and el-enriched): 50% done
- Data SingleElectron: running
- Data SingleMuon: submitted

**Comment by emanueledimarco** [comment]
Size calculated on a fair number of events:

- data (single electron): [0.44 kB/event](https://emanuele.web.cern.ch/emanuele/Analysis/WMass/13TeV/trees/full_V3/data_singleel.html)
- mc (Z+jets w/o LHE weights): [0.70 kB/event](https://emanuele.web.cern.ch/emanuele/Analysis/WMass/13TeV/trees/full_V3/mc_zjets.html)
- mc (W+jets with LHE weights): [2.54 kB/event](https://emanuele.web.cern.ch/emanuele/Analysis/WMass/13TeV/trees/full_V3/mcwithlhe_wjets.html)

**Comment by emanueledimarco** [comment]
- MC with fake rate measurement selection submitted

**Comment by emanueledimarco** [comment]
MC Summer 16 fully done. For the time being, trees in:
- /eos/cms/store/group/dpg_ecal/comm_ecal/localreco/TREES_1LEP_80X_V3

**Comment by emanueledimarco** [comment]
MC Summer16 with the fake-rate skim done.
Selection: 
- at least one pair lep-jet with 
   - jet.pt() > 30 and abs(jet.eta()) < 2.4
   - loose lepton with pt>15 GeV
- deltaR(lep.eta(),lep.phi(), jet.eta(), jet.phi()) > 0.7

Trees in: /eos/cms/store/group/dpg_ecal/comm_ecal/localreco/TREES_1LEP_80X_V3_FR

**Comment by cippy** [comment]
Hi,

will the "*part*" chunks be merged together at some point or do we keep 
them as they are?

**Comment by emanueledimarco** [comment]
The ones which have _part are for the samples that are very big, and I have done the merging making groups not exceeding 4 or 5 Gb each. I think that we should leave them separated, and treat them as the samples which have extensions in DAS (XXX_ext1 etc). 

In the analysis framework you can add extensions with "+" in the config file.

**Comment by emanueledimarco** [comment]
Summary:
- signal skim:
MC and data single electron: /eos/cms/store/group/dpg_ecal/comm_ecal/localreco/TREES_1LEP_80X_V3
   * singleMuon almost done, to be merged
- Fake rate skim:
/eos/cms/store/group/dpg_ecal/comm_ecal/localreco/TREES_1LEP_80X_V3_FR
   * MC, DoubleEG, DoubleMu done

**Comment by emanueledimarco** [comment]
SingleMu done 100%, merging...

**Comment by emanueledimarco** [comment]
SingleMuon dataset merged. Trees in the same area of the others:
/eos/cms/store/group/dpg_ecal/comm_ecal/localreco/TREES_1LEP_80X_V3
@mdunser (please check if everything is fine)

**Comment by emanueledimarco** [comment]
In principle all the needed samples to setup analysis are done.
